name: tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      
      - name: check go.mod
        run: |
          set -e
          go mod tidy
          output=$(git status -s)
          if [ -z "${output}" ]; then
            exit 0
          fi
          echo "$output"
          exit 1

      - name: fmt check
        run: |
          set -e
          files=$(gofmt -l .)
          if [ -z "${files}" ]; then
            exit 0
          fi
          echo "$files"
          exit 1

      - name: run tests
        run: |
          go test ./...

      - name: test coverage
        run: |
          COVERAGE_THRESHOLD=85
          go test -coverprofile=cover.out ./...
          coverage=$(go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          coverageInt=${coverage%.*}
          [ "$coverageInt" -ge "$COVERAGE_THRESHOLD" ]
